// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";

function App(Props) {
  return React.createElement("div", undefined, "hello");
}

var make = App;

export {
  make ,
  
}
/* react Not a pure module */
