// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as IndexJs from "./index.js";

function scrollToIndex2(prim, prim$1) {
  IndexJs.scrollToIndex(prim, prim$1);
  
}

IndexJs.scrollToIndex(1, undefined);

var res;

export {
  scrollToIndex2 ,
  res ,
  
}
/*  Not a pure module */
